blockbot: remove unused env variable
redbrick/nomad pull request #73
Opened 2024-11-14 10:42 UTC by aydenjahola

this doesnt need to exist, as by default debug is false, adding this option is not necessary

2024-11-14 11:32 UTC, HypnoAnt commented
Why maintain the job in 2 locations?

2024-11-14 11:35 UTC, HypnoAnt requested changes

2024-11-14 11:35 UTC, HypnoAnt commented on jobs/webgroup/blockbot.hcl
> +DEBUG= # empty means false
Why not just declare it as False. If you are adding an extra comment to say that it's false then just declare it as false.

2024-11-18 15:14 UTC, wizzdom requested changes
Better to remove this job as it is already maintained on the blockbot repo

2025-01-03 19:45 UTC, closed without merging